/* Juan */
CREATE TABLE labels (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR NOT NULL,
    color VARCHAR NOT NULL
);

CREATE TABLE books (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publish_date DATE NOT NULL,
    archived BOOLEAN NOT NULL,
    publisher VARCHAR NOT NULL,
    label_id INT,
    genre_id INT,
    author_id INT,
    source_id INT,
    CONSTRAINT fk_book_label
      FOREIGN KEY(label_id) 
	  REFERENCES labels(id)
	  ON DELETE SET NULL,
    CONSTRAINT fk_book_genre
      FOREIGN KEY(genre_id) 
	  REFERENCES genres(id)
	  ON DELETE SET NULL,
    CONSTRAINT fk_book_author
      FOREIGN KEY(author_id) 
	  REFERENCES authors(id)
	  ON DELETE SET NULL,
    CONSTRAINT fk_book_source
      FOREIGN KEY(source_id) 
	  REFERENCES sources(id)
	  ON DELETE SET NULL
);

CREATE INDEX IDX_book_label ON books(label_id);
CREATE INDEX IDX_book_genre ON books(genre_id);
CREATE INDEX IDX_book_author ON books(author_id);
CREATE INDEX IDX_book_source ON books(source_id);

/* Saadat */

/* Chris */

/* Alejandro */

CREATE TABLE movies (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publish_date DATE NOT NULL,
    archived BOOLEAN NOT NULL,
    silent BOOLEAN NOT NULL,
    label_id INT,
    genre_id INT,
    author_id INT,
    source_id INT,
    CONSTRAINT fk_movie_label FOREIGN KEY(label_id) REFERENCES labels(id) ON DELETE SET NULL,
    CONSTRAINT fk_movie_genre FOREIGN KEY(genre_id) REFERENCES genres(id) ON DELETE SET NULL,
    CONSTRAINT fk_movie_author FOREIGN KEY(author_id) REFERENCES authors(id) ON DELETE SET NULL,
    CONSTRAINT fk_movie_source FOREIGN KEY(source_id) REFERENCES sources(id) ON DELETE SET NULL
);

CREATE TABLE sources (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
);

